// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Y-7MuvbGzkVdrf-QRzk3ETCi2ABw0Cg',
    appId: '1:1009297431719:web:e7d2f509103b25b658cf82',
    messagingSenderId: '1009297431719',
    projectId: 'finalprojectnti',
    authDomain: 'finalprojectnti.firebaseapp.com',
    storageBucket: 'finalprojectnti.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiHfOCk9ujAyhHDR5hjruYKrbV4J_ETSg',
    appId: '1:1009297431719:android:84e840a61cfb370258cf82',
    messagingSenderId: '1009297431719',
    projectId: 'finalprojectnti',
    storageBucket: 'finalprojectnti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAnEsb4re-tluwHQuZ10ZDtVHHn8EWBCI',
    appId: '1:1009297431719:ios:5eb49bfe12994b0958cf82',
    messagingSenderId: '1009297431719',
    projectId: 'finalprojectnti',
    storageBucket: 'finalprojectnti.firebasestorage.app',
    iosBundleId: 'com.example.providerTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAnEsb4re-tluwHQuZ10ZDtVHHn8EWBCI',
    appId: '1:1009297431719:ios:5eb49bfe12994b0958cf82',
    messagingSenderId: '1009297431719',
    projectId: 'finalprojectnti',
    storageBucket: 'finalprojectnti.firebasestorage.app',
    iosBundleId: 'com.example.providerTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Y-7MuvbGzkVdrf-QRzk3ETCi2ABw0Cg',
    appId: '1:1009297431719:web:4df80937334cbdd658cf82',
    messagingSenderId: '1009297431719',
    projectId: 'finalprojectnti',
    authDomain: 'finalprojectnti.firebaseapp.com',
    storageBucket: 'finalprojectnti.firebasestorage.app',
  );
}
